// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // only connection URLs (and shadow DB) belong here
    url: env('DATABASE_URL'),
    // optional: shadowDatabaseUrl: env('SHADOW_DATABASE_URL'),
  },
});
